#SPDX-License-Identifier: MIT-0
---
# tasks file for raspap

- name: Manage RTL8811AU driver
  ansible.builtin.import_tasks: rtl8811au.yml
  when: raspap_manage_rtl8811au | bool

- name: Install RaspAP using official installer
  ansible.builtin.shell: curl -sL https://install.raspap.com | bash
  args:
    executable: /bin/bash
    creates: /etc/raspap
  become: true
  when: raspap_install | bool
