[prod]
; Raspberry 5 Homelab Main Server
srvprod01
; Raspberry 4 Sovrana
srvprod02
; Raspberry 4 Forgejo Runner
srvprod03
[lab]
srvlab01

[over_jump_host]
192.168.1.157 ansible_ssh_common_args='-J pi@server2'

[sovrana]
; Lenovo ThinkCenter Sovrana
srvprod04