#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/debian_hardening
# SSH policy
# valid values: keys_only | password_only | keys_and_password
debian_hardening_ssh_auth_mode: "keys_only"
debian_hardening_ssh_permit_root_login: "no"      # "no" | "prohibit-password" | "yes"
debian_hardening_ssh_max_auth_tries: 3
debian_hardening_ssh_login_grace_time: "30s"
debian_hardening_ssh_client_alive_interval: 300
debian_hardening_ssh_client_alive_count_max: 2
debian_hardening_ssh_allow_groups: ["sudo"]

# Weekly upgrades instead of daily
debian_hardening_enable_weekly_upgrade: true
debian_hardening_disable_apt_daily_index_timer: true

# Optional service disables
debian_hardening_disable_services: []

debian_hardening_logs_max_size: "100M"
debian_hardening_logs_retention: "1month"
debian_hardening_enable_persistent_logs: false
