---
- name: Site playbook to run arbitrary roles
  hosts: all
  gather_facts: true
  tasks:
    - name: Include roles defined in the host variable "assigned_roles"
      include_role:
        name: "{{ item }}"
      loop: "{{ assigned_roles | default([]) }}"
