#SPDX-License-Identifier: MIT-0
---
# vars for komodo_periphery

# image tags / host
PERIPHERY_VERSION: "{{ komodo_periphery_version }}"

# derived paths
PERIPHERY_PATH: "{{ komodo_periphery_deployment_directory }}/periphery"
PERIPHERY_KEYS_PATH: "{{ komodo_periphery_deployment_directory }}/periphery_keys"

# runtime variables passed into the container
PERIPHERY_CORE_PUBLIC_KEY: "{{ komodo_periphery_secret_core_public_key }}"
PERIPHERY_CORE_ADDRESS: "{{ komodo_periphery_core_address }}"
PERIPHERY_CONNECT_AS: "{{ komodo_periphery_connect_as }}"

# Optional onboarding key and feature toggles
PERIPHERY_ONBOARDING_KEY: "{{ komodo_periphery_secret_onboarding_key | default('') }}"
PERIPHERY_DISABLE_TERMINALS: "{{ komodo_periphery_disable_terminals }}"
PERIPHERY_DISABLE_CONTAINER_EXEC: "{{ komodo_periphery_disable_container_exec }}"