#SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: Enrico Cirignaco
  description: Install and configure Docker Engine on Debian hosts.
  license: MIT-0
  min_ansible_version: "2.14"
  galaxy_tags:
    - docker
    - containers
    - debian
    - engine

dependencies: []
